name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Write PG url to Prod Properties-file
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: './src/main/resources/application-prod.properties'
          property: 'spring.datasource.url'
          value: ${{secrets.HEROKU_PG_URL}}
      - name: Write PG user to Prod Properties-file
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: './src/main/resources/application-prod.properties'
          property: 'spring.datasource.username'
          value: ${{secrets.HEROKU_PG_USER}}
      - name: Write PG password to Prod Properties-file
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: './src/main/resources/application-prod.properties'
          property: 'spring.datasource.password'
          value: ${{secrets.HEROKU_PG_PASS}}
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'edh-pod-generator-api'
          heroku_email: 'sean.m.mcquaid@gmail.com'