name: Pull Request
on:
  pull_request:
    branches: [main]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GHA
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.2'
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
          postgresql db: 'podGenerator'
          postgresql user: ${{secrets.POSTGRES_USER}}
          postgresql password: ${{secrets.POSTGRES_PASSWORD}}
      - name: Run Unit Tests
        run: mvn test